active = false;
speaker = "";
dialogue = "";
spr_speaker_avatar = noone
sprite_index = spr_chatbox; 
dialogue_pages = noone
global.dialogue_pages1 = ["This is frist", "This is second", "Last one good luck."]; 
global.dialogue_pages_bell = ["This is a bell", "You can use it to shoot", "Good luck for your journey."]
global.dialogue_pages_coal = ["This is a coal", "I don't know how to use it", "Good luck for your journey."]
current_page = 0;
